/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cis44groupproject;

import static cis44groupproject.Main.toArrayCasting;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class RankingWindow extends javax.swing.JFrame {

    /**
     * Creates new form RankingWindow
     */
     LinkedBag<Student> studentBag = new LinkedBag<>();
     
    public RankingWindow( LinkedBag<Student> studentBag) {
        this.studentBag = studentBag;
        initComponents();
        AddDataToTable();
    }

    RankingWindow() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
 void AddDataToTable(){
     
        Student[] studentArray = toArrayCasting(studentBag);
        //Student[] sortedArray = accendingSort(studentArray);
         DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
//         
//        
////         Vector v1 = new Vector();
////         Vector v2 = new Vector();
////         Vector v3 = new Vector();
//
//         Student currentStudent;
//         
//         
//         
//
         for(int i=0 ; i<studentArray.length; i++)
         {
             Vector v = new Vector();
             v.add(studentArray[i].getfName());
             v.add(studentArray[i].getlName());
             v.add(studentArray[i].getGPA());
             dt.addRow(v);
         }
         
         
//         DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
//         
//        
//         Vector v1 = new Vector();
//         Vector v2 = new Vector();
//         Vector v3 = new Vector();
//
//         
//         v1.add("e");
//         v1.add("f");
//         v1.add("6.00");
//         
//         v2.add("c");
//         v2.add("d");
//         v2.add("3.00");
//         
//         v3.add("a");
//         v3.add("b");
//         v3.add("4.00");
//    
//         dt.addRow(v1);
//         dt.addRow(v3);
//         dt.addRow(v2);
//        
  
     }
 public static <T> Student[] toArrayCasting(LinkedBag<T> inputBag)
    {
        Object[] rawStudentData = inputBag.toArray();
        Student currentStudent;
        Student[] toArrayStudent = new Student[rawStudentData.length];
        for (int i = 0; i < rawStudentData.length; i++) {
            currentStudent = (Student) rawStudentData[i];
            toArrayStudent[i] = currentStudent;
        }
        return toArrayStudent;
    }
 
  public static <T extends Comparable<T>> T[] accendingSort(T[] arr) {
        T[] sortedList = arr;
        for (T item : sortedList) {
            for (int i = 0; i < sortedList.length - 1; i++) {
                if (sortedList[i].compareTo(sortedList[i + 1]) > 0) {
                    T temp = arr[i];
                    sortedList[i] = arr[i + 1];
                    sortedList[i + 1] = temp;
                }
            }
        }
        return sortedList;
    }
  
      public static <T extends Comparable<T>> T[] descendingSort(T[] arr) {
        T[] sortedList = arr;
        for (T item : sortedList) {
            for (int i = 0; i < sortedList.length - 1; i++) {
                if (sortedList[i].compareTo(sortedList[i + 1]) < 0) {
                    T temp = arr[i];
                    sortedList[i] = arr[i + 1];
                    sortedList[i + 1] = temp;
                }
            }
        }
        return sortedList;
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        sortButton = new javax.swing.JButton();
        sortButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("3. Ranking");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(678, 428));

        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First", "Last", "GPA"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sortButton.setBackground(new java.awt.Color(255, 255, 255));
        sortButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sortButton.setText("Descending");
        sortButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortButtonActionPerformed(evt);
            }
        });

        sortButton2.setBackground(new java.awt.Color(255, 255, 255));
        sortButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sortButton2.setText("Ascending");
        sortButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 62, 70));
        jPanel1.setPreferredSize(new java.awt.Dimension(678, 122));
        jPanel1.setRequestFocusEnabled(false);

        jPanel2.setBackground(new java.awt.Color(104, 216, 192));
        jPanel2.setPreferredSize(new java.awt.Dimension(678, 44));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("3. Ranking");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(sortButton)
                .addGap(18, 18, 18)
                .addComponent(sortButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(sortButton)
                    .addComponent(sortButton2))
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.hide();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortButtonActionPerformed
        // TODO add your handling code here
       
        
         Student[] studentArray = toArrayCasting(studentBag);
        Student[] sortedArray = descendingSort(studentArray);
         DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
          dt.setRowCount(0);

         for(int i=0 ; i<sortedArray.length; i++)
         {
             
             Vector v = new Vector();
             v.add(studentArray[i].getfName());
             v.add(studentArray[i].getlName());
             v.add(studentArray[i].getGPA());
             dt.addRow(v);
         }
    }//GEN-LAST:event_sortButtonActionPerformed

    private void sortButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortButton2ActionPerformed
        // TODO add your handling code here:
         Student[] studentArray = toArrayCasting(studentBag);
        Student[] sortedArray = accendingSort(studentArray);
         DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
          dt.setRowCount(0);

         for(int i=0 ; i<sortedArray.length; i++)
         {
             
             Vector v = new Vector();
             v.add(studentArray[i].getfName());
             v.add(studentArray[i].getlName());
             v.add(studentArray[i].getGPA());
             dt.addRow(v);
         }
    }//GEN-LAST:event_sortButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RankingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RankingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RankingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RankingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RankingWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton sortButton;
    private javax.swing.JButton sortButton2;
    // End of variables declaration//GEN-END:variables
}
